export const TOGGLE_ADD_HERO_ARE = 'TOGGLE_ADD_HERO_ARE';

export const NETWORK_ERROR = 'NETWORK_ERROR';

export const GET_HERO_REQUEST = 'GET_HERO_REQUEST';
export const ADD_HERO_REQUEST = 'ADD_HERO_REQUEST';
export const ADD_IMG_REQUEST = 'ADD_IMG_REQUEST';
export const ADD_HERO_WITH_IMG_REQUEST = 'ADD_HERO_WITH_IMG_REQUEST';
export const UPDATE_HERO_REQUEST = 'UPDATE_HERO_REQUEST';
export const DELETE_HERO_REQUEST = 'DELETE_HERO_REQUEST';
export const DELETE_IMG_REQUEST = 'DELETE_IMG_REQUEST';

export const SET_QUERY_DATA = 'SET_QUERY_DATA';
